app:
  codeName: ${APP_CODENAME}
env: local
postgres:
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  port: ${DB_PORT}
  host: ${DB_HOST}
  name: ${DB_NAME}
  dialect: postgres
  poolMin: 2
  poolMax: 10
httpServer:
  addr: ${SERVER_ADDR}
  port: ${SERVER_PORT}
  timeout: 4s
  idleTimeout: 60s
  shutDownTimeout: 5s
service:
  timeout: 5s
jwt:
  secret: ${JWT_SECRET}
  accessExp: ${JWT_ACCESS_EXP}
  refreshExp: ${JWT_REFRESH_EXP}